### ISSUE TITLE
GUIs are incomplete in Carla plugin host

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#109]
I've always had a problem with Calf plugins whe running the min Carla - the GUIs were lacking graphs.

I've reported this in Carla Github previously: https://github.com/falkTX/Carla/issues/389
It seems that this problem occurs when the Carla is using a GUI-bridge (on by default).
The Analyzer seems to be forcing a GUI bridge even if it's disabled in Carla's settings - it's the only Calf plugin that's "resistant" to this workaround.

What can be done on both sides to fix this problem?

## Stable versions
**(from KX Studio repos: calf-plugins package)**

Compressor:

![selection_207](https://cloud.githubusercontent.com/assets/491704/21181026/26998e6a-c1fc-11e6-94d6-76f413188b90.png)

Deesser:

![selection_208](https://cloud.githubusercontent.com/assets/491704/21181034/32e0d30e-c1fc-11e6-9282-6d6758af8d34.png)

Equalizer:

![selection_209](https://cloud.githubusercontent.com/assets/491704/21181051/4c61824c-c1fc-11e6-92c3-23a45c5e715b.png)

Analyzer:

![selection_206](https://cloud.githubusercontent.com/assets/491704/21181434/31a28dbe-c1fe-11e6-8322-0eae22d2174e.png)

## Github versions
**(from KX Studio repos: calf-plugins-git package)**

Compressor:

![selection_211](https://cloud.githubusercontent.com/assets/491704/21181499/813a93bc-c1fe-11e6-9b09-bc81e742fca4.png)

Deesser:

![selection_212](https://cloud.githubusercontent.com/assets/491704/21181505/8d60618a-c1fe-11e6-9cd2-82fcd9649a7a.png)

Equalizer:

![selection_213](https://cloud.githubusercontent.com/assets/491704/21181521/9fee83ae-c1fe-11e6-824f-97e269ded636.png)

Analyzer:

![selection_210](https://cloud.githubusercontent.com/assets/491704/21181477/7028d1d8-c1fe-11e6-8320-0958bed6f961.png)

**Comment by falkTX** [comment]
Using the (default) plugin bridge, what you get are the expected results. Except for the analyzer.
The logic on carla that checks for analyzer might be wrong.

**Comment by boomshop** [comment]
The main problem is that Calf still relies on instance-access which sucks and is a cause for different other problems as well. As soon as we have LV2 atoms support we would be able to communicate all graphs data through LV2 directly. Problem is: we didn't find the time to implement it by now and I can't make any promises when it will be available.

**Comment by unfa** [comment]
Thank you @falkTX and @boomshop for giving feedback.
This problem doesn't affect the sound at all, so I can live with it.
I'm using Calf plugins withing Carla all the time anyway.

**Comment by sadko4u** [comment]
>The main problem is that Calf still relies on instance-access which sucks and is a cause for different other problems as well.

I wouldn't say so. According to my experience, LV2 Atoms currently have extremely slow implementation in Ardour and were also slow in Carla. So It is very easy to get numerous 'Error to writing plugin UI' messages, especially on low latency settings of JACK.

**Comment by boomshop** [comment]
Hm okay, haven't tested things so far so any input or consideration is greatly appreciated. Sounds like it wouldn't make too much sense to try to hand over multiple arrays of per-pixel values at 60 frames a second to draw different EQ graphs together with a real-time analyzer in the background?

**Comment by sadko4u** [comment]
I use 25 FPS, and in most cases VST version of plugins works faster (and takes less CPU cycles) than LV2 because doesn't need to transfer atoms from DSP to UI.
For example, if we have a mesh of two coordinates of 400 points, we will get one frame for graph of 2 * 400 * sizeof(float) = 3200 bytes. If we transfer 16 different meshes, we already get 51200 bytes. And we should do this 25 times per second, it's 1280000 bytes/second or ~1,3 MByte. For modern computers it's not too much but due to some reasons it works not so well. Also we had issues with Atom (and also with URID) transport in Carla. Don't know currently about did falkTX completely fix this or not.

**Comment by sadko4u** [comment]
I don't try say that LV2 is bad or atoms are bad or something else. I just only say that current implementation of LV2 by hosts is not optimal. According to my experience, bulk operations are always faster than single. For example, we have a nice URID interface. But there is no possibility to call batch function with 100500 arguments to get 100500 URIDs simultaneously. We have to call map() 100500 times instead. And this works slow. Also with atoms. We have complex mechanism to communicate with UI and other DSP modules but it's not well documented. For example, to properly send Patch messages, I had to deelply inspect Ardour code and watch how it does transfer them (shorly: the code looks too hacky).

**Comment by boomshop** [comment]
Thanks a lot for explanations and insight!

**Comment by unfa** [comment]
So it's not an internal flaw of LV2, it's just the way this is implemented on most hosts?

**Comment by sadko4u** [comment]
No, it's not a flaw. But there are some moments to criticize this standard.
Because not all solutions are simple as they could be, and that makes the implementation of both host and plugin harder.

For example, new MIDI standard requires to send MIDI events via atom port, and this also can be performed via common DSP<->UI atom exchange port. But not all host do properly handle it. For example, Ardour ignored minimumSize attribute of resizePort extension and went to buffer overflows until we solved this problem with Robin Gareus. Also there was a problem in Carla that it could not handle one individual atom larger than 8kbytes and flooded with warning messages into log.

As the counterpart, with VST2.4 I never had such problems: here's buffer for UI, I can write to it on any DSP iteration and then notify the UI that the data has been updated. Also I have special callback functions to communicate with MIDI devices.

As the second example, I can recall the new LV2 Inline Display extension. Yes, it's cool and really usable. But it brokes the entire paradigm of LV2 that says: UI should be separated from DSP and communicate with it by using atom ports (MVC). Here we get that DSP modules also implement part of some UI if it supports this extension. Also I currently don't understand why the MVC paradigm was taken. Because if there is UI for the DSP, it's in 99.9% provided by the developer of the DSP. Have you ever seen the case where the 3rd party developer provided LV2 UI to some DSP module? Or have you ever seen when the UI that communicates with DSP was executed on another machine? There should be huge good reasons to do this because non-direct communication takes time and CPU to perform it.

**Comment by boomshop** [comment]
What you say is true. But let me give some examples for 

> Have you ever seen the case where the 3rd party developer provided LV2 UI to some DSP module?

[MOD](https://1.bp.blogspot.com/-DeEZb09183w/VCk4HvctQEI/AAAAAAAACwc/lPTZyeabpYc/s1600/mock.png)
[Guitarix](http://jeffhendricks.net/wp-content/uploads/2014/06/Guitarix1.png) (okay, old screener, so LADSPA)
[Carla](http://www.linux-community.de/var/ezwebin_site/storage/images/internal/artikel/print-artikel/linuxuser/2015/04/klangwunder/abbildung-3/2634089-1-ger-DE/Abbildung-31_lightbox.png)

LMMS still uses LADSPA I guess. And last not least my own company doing (non-LV2) remote UI for different manufacturers [1](http://www.live-production.tv/sites/default/files/styles/original_image_with_copyright/public/L1080329.JPG?itok=A-n3ia3w), [2](http://salzbrenner.com/images/broschueren/SALZBRENNER_NIO_xcel_de.pdf), [3](https://upload.wikimedia.org/wikipedia/commons/9/98/Stagetec_AURUS_03.jpg) (work in progress)

So at least in pro audio world there's a huge demand for protocols and technology like LV2, just that LV2 is not sufficient, comfortable or flexible enough. VST technology is outdated these days and only works in environments like stationary DAW which is a quite small market share.

**Comment by sadko4u** [comment]
Markus, you gave examples, but the UI is a part of the project you ment. I ment the case when the UI is independent project made by 3rd party developer that is not moved into upstream.
I can't say sure about MOD because I'm not familiar with it.

**Comment by falkTX** [comment]
PR #113 addresses this issue by making analyzer ui require instance-data (instead of being optional).
We can make more plugin UIs require it too, if it's essential.
afaik only analyzer becomes useless without it.

**Comment by boomshop** [comment]
Hey Vladimir,
I meant the Calf plugins as LV2 instances in Guitarix and Carla with the UI generated by the host. BTW - a bit OT - if you find some time it would be nice if you could look into #88 if there's anything you can do about.

Hey Filipe,
thanks a lot for the pull request! I will modify it when I find the time since we should have instance access as a switch in metadata.cpp or metadata.h which would make things a bit more consistent and comfortable.

**Comment by falkTX** [comment]
btw, I just noticed the fluidsynth plugin requires instance access too.
have that set as part of the metadata is a very nice idea.
