### ISSUE TITLE
Using Calf LV2 plugins with Ardour under Windows?

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#145]
I have heard that Calf LV2 plugins use the GTK toolkit and because of that using them under Windows is impossible.

Is that true?

What can be done about that?

**Comment by boomshop** [comment]
True, we're using GTK. I guess nobody of us cares about Windows enough to spend this huge amount of time to re-invent the whole user interface.

**Comment by borgdylan** [comment]
AFAIK GTK runs under Windows and also macOS. Ardour itself uses GTK as well.

**Comment by x42** [comment]
I've investigated this in the past (for guitarix, which also uses GTK) and it's near impossible.

Unless you use ABI (binary) compatible gtk, it won't work.
Furthermore GTK cannot be statically linked, so the plugins cannot be self-contained.

The only option would be to compile both the plugin-host (Ardour) and the plugins with the exact same compiler and same gtk-version (and all of gtk's dependencies) and keep them in sync. While that's feasible on OSX for self-builds, it's worse on windows since linking is done using ordinals, not symbol-names.

**Comment by unfa** [comment]
So it's pretty much a no-go, unless a dedicated developer comes in to spend his lifetime on this one thing.

I guess we can close this issue now.
