### ISSUE TITLE
What is Calf Limiter's ASC function really doing?

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#167]
I have tried learning this, I've read the docs I still have no idea what that is.

In the manual I found this:

> ASC: When gain reduction is always needed ASC takes care of releasing to an average reduction level rather than reaching a reduction of 0 in the release time
> ASC Level: Select how much the release time is affected by ASC, 0 means nearly no changes in release time while 1 produces higher release times

Still I don't quite understand many things.

Could someone explain to me what ASC is doing on some examples?
What that knobs does?
What the LED is indicting?
How can I use this consciously?
Why is it on by default? Isn't this going to make my limiter work unpredictibly?
What does the name stand for? Auto Sustain Control?

So many questions, so little answers so far! :)

![image](https://user-images.githubusercontent.com/491704/35189651-b25eb534-fe4f-11e7-9a31-14bac17e9899.png)

**Comment by boomshop** [comment]
First of all a deeper understanding of how the release works is necessary. The release time is the time needed to return from possible gain reduction after a peak appeared back to no reduction. Now let's look at the case when permanent gain reduction of e.g. 6dB appears. If a peak appears in this situation the release time would be calculated to reach zero. Since it isn't able to go back to no reduction (because on average it just goes back to the permanent 6dB) the time for the release would on average be shorter than set by the user. That's what ASC is developed for. It keeps track of the average gain reduction (in fact it keeps track of the average signal strength, but for this explanation seeing it as reduction is easier for understanding) and takes this as the final state of the reduction while calculating the release slope. The LED displays when the ASC slope is used instead of the normal one. This happens if the ASC slope is smaller than the normal one. The value of the `ASC Level` knob sets the amount of the ASC slope before the comparison. The higher this value is set the more often the ASC slope is used instead of the normal one. This results in a temporary higher release time for this peak, if releasing back to no reduction.

- Normal behavior: release time 5ms from -12 dB peak reduction to no reduction
- ASC behavior: release time 5ms from -12 dB to -6 dB (average level)

![asc](https://user-images.githubusercontent.com/12529902/35365329-48020330-0174-11e8-9b99-021b85b24529.png)
(The image doesn't care about logarithm)

This results in a much softer limiting with more smooth release processes whatever material is stuffed in there. A little less loudness but audibly less distortion. If only few peaks happen while the limiter isn't doing anything most of the time, enabling ASC doesn't affect the limiting process. It only hits in as soon as there is permanent gain reduction and evens it out, that's why it is enabled by default.

**Comment by boomshop** [comment]
Oh and I forgot: ASC = Adaptive Slope Control

**Comment by mikhailnov** [comment]
Thanks for explanation... it was useful

**Comment by trebmuh** [comment]
Nice explanation @boomshop :+1: 

Would you agree that it'd be a great addition to the manual? (I can make it so if you're +1 with it)

**Comment by boomshop** [comment]
Feel free, i'd merge a pull request.

**Comment by trebmuh** [comment]
@boomshop done : https://github.com/calf-studio-gear/calf/pull/189
