### ISSUE TITLE
JACK MIDI utilities plugin

### ISSUE THREAD

**Issue by techdude1996** [calf-studio-gear/calf#199]
I am a software engineer, and would like to add a plugin myself, but don't know where to start. I want to create a MIDI utility for use in Calf Studios that would go under **Add plugin -> Utilities**. I would like to create a plugin to manually override program numbers that are sent through the MIDI channel that represent different instruments.

Example: I use Musescore to create my music scores and use it as the midi controller for external instruments. When I feed Musescore's MIDI out to an external synth, like AMSynth, the preset is changed from what I had selected when I hit play on Musescore. The ability to manually override metadata like parts in the MIDI signal would be very helpful here. The same happens with Calf's Fluidsynth. When I select an instrument program from the soundfont, Musescore changes it back when I hit play.

I am willing to create this plugin myself, I just need to know where to start. And who knows? I might make a few more utilities down the road. Also, I have already forked the repo.

**Comment by boomshop** [comment]
There already are a couple of MIDI manipulating programs out there afaik (try X42 MIDI filter for example https://github.com/x42/midifilter.lv2 / https://x42.github.io/midifilter.lv2/), my feeling is there's no need to re-invent the wheel. You could ask at http://linuxmusicians.com for more information since I'm not into the MIDI world that much.

If it's more about coding it would be much easier to start from scratch for this kind of plug-in since Calf is a huge piece of software with lots of obstacles. And it's unlikely that such a highly specific plug-in would make it into upstream. To have something to start with you could try JUCE which is an audio/midi framework making it easy to build audio/midi plug-ins although I wouldn't recommend it to be used in the wild.

OTOH creating an LV2 plug-in isn't rocket science, I would recommend to try that first.
