### ISSUE TITLE
Feature request: please add 0.0.60 GUI theme to Style menu

### ISSUE THREAD

**Issue by jrigg** [calf-studio-gear/calf#29]
Please add the 0.0.60 GUI theme to the Style menu. The indicators around the rotary controls in the 0.0.19 style which has replaced it just look broken and are confusing to look at. I'll add that I usually avoid fancy plugin GUIs as I find them visually distracting. The 0.0.60 style is one of the few I can tolerate using ;-)

**Comment by boomshop** [comment]
The fancy but information-lacking rings around the knobs will not return. What do you mean by "broken"?

**Comment by jrigg** [comment]
The black marks on the rings around the knobs look (to me) like burned out sections in a hardware LED bar. I find it easier to see approximately what the  control is set to when in a hurry with the 0.0.60 style. It could be argued that hardly any real-life hardware has such things, but I would counter that by saying this isn't hardware so a different approach is justified.

**Comment by boomshop** [comment]
We already had this discussion internally and boiled it down to your last statement (not hardware) while claiming it some kind of e-ink. The new approach is a compromise between letting any user (newbie or veteran) spot the actual position easier than with just the tick on the knob itself on one hand (the use case before the introduction of the new drawing method since the old stylish knobs made it a little harder to spot the tick on the knob itself) and giving versed users the capability to see the relationship of the actual value against some landmarks in the overall scale. We think that this way the ring gains much more value than just looking fancy. The philosophy is to look aesthetic *and* to provide a usable interface for n00bs, average and power users.

As you may have noticed - a lot of "fancyness" had to clear the way for more information - e.g. there's no more lighting effects in the indicators - which I personally liked but which would be kooky to implement here. The new clinical white knobs style is much more sheer which adds more clarity, too. So normally the new style should accommodate your likings since it is much cleaner and less fancy than before and the chrome in knobs and toggles was reduced to just shapes instead of glossy plastic attached to sanded aluminium with cyan shiny LED lighting effects around.

Nonetheless I think the new approach looks more up-to-date when talking about prettiness, but that's always in the eye of the beholder and obviously not your criteria. Less ornaments, more clearness and more information - isn't that what users disliking fancy stuff are searching for?

**Comment by jrigg** [comment]
All fair points.
