### ISSUE TITLE
Feature request : EQ matching

### ISSUE THREAD

**Issue by MrHeadwar** [calf-studio-gear/calf#41]
Hi and thanks for the Calf suite !

I'd like to be able to do EQ matching (cf https://www.youtube.com/watch?v=YO_7Q_BmKls) with Calf x-Band Equalizers. My naive guess is that it would add only 2 buttons : 
 - "take EQ profile"
 - "match against last profile", which would "substract" the EQs.
Well, I'm sure it's a LOT more complicated than that but it would be a great addition to the (already great) EQs.

Best Regards

**Comment by boomshop** [comment]
This only works well with EQs using FFT - which Calf doesn't have.

**Comment by MrHeadwar** [comment]
Maybe (just maybe) the FFT could only be used in the analysis part, and then converted to some kind of a time domain response curve, and the EQ would still be in TD and not an iFFT ?

**Comment by boomshop** [comment]
Surely the FFT has to be used for analysis, but that's not the problem. Please take a look at the response curve the EQ in your example has to accomplish - I'm counting more than 24 peaks that are all influencing themselves. There's no such thing as a frequency domain response curve, the displayed one is just a summary of all bands which you can't simply "reverse".

**Comment by MrHeadwar** [comment]
OK. Thanks for having investigated my request and for your explanations.

**Comment by boomshop** [comment]
Actually I'm talking to one of my associates who is a highly skilled mathematician and we're discussing the issue probably tonight.  I'll let you know about the results. What we discussed already is that this problem is some kind of a standard problem and there's not "the solution" for it. So we'll take a closer look on the math behind the filters to see if there's at least some kind of approximation. Please don't expect anything but it's worth to discuss it.

**Comment by MrHeadwar** [comment]
Great to read ! Should I reopen the issue or is it OK ? Thanks again, hope your friend will have a great idea !

**Comment by boomshop** [comment]
I'm aware of this issue so no need for any further action atm.

**Comment by boomshop** [comment]
Okay, we discussed things today. As I already mentioned it seems to be a high-level mathematical problem. In general there's a c++ lib called ceres which is of great help to solve one of the major problems. But that's only one single part of the story, lots of tripping hazards in the way. It would take a couple of days in fulltime for a skilled mathematician to solve it. In the end we would only have some kind of approximation since we lack of filters. More filters would make the processing time in every aspect even worse. So there's no realistic (or doable) solution for this problem without using FFT-based equalizers (which introduce other weaknesses).

Since we already work with FFT perhaps there will be a Calf mastering EQ in the future which should be capable of frequency response matching, but for now I have to belie your expectations :(

**Comment by MrHeadwar** [comment]
Well, it was worth asking ;) Thanks for having taken the time to look into it in such details, and for your work on the plugins suite !
