### ISSUE TITLE
Calf plugins for Mac OS X?

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#72]
Hey! I do all my private stuff on Linux, but the studio I work in uses Mac OS X and Cubase.

I miss the Calf plugins there a lot - is it possible to make Calf plugins availabile for Mac users too?

**Comment by boomshop** [comment]
Hey unfa,

it would mean to make them VST or AU at least but I fear there are lots of other traps until it compiles on MacOSX as well. Since none of us has a) a Mac or b) any interest in proprietary formats like VST and AU I'm sorry to say that I fear there's no real endeavor from within the current devs at all.

I'll leave the request open, probably someone else is willing to step in some day.

**Comment by david0** [comment]
Hey unfa,
there is a homebrew formula for building calf on os in my homebrew-tap (
https://github.com/david0/homebrew-audio).

I would suggest you either use the LV2 with generic UI only or use the GTK
UI via calfjackhost.
Running the GTK UI in ardour is not stable since the OS X linker dos not
support the -nodelete flag.

**Comment by boomshop** [comment]
Oh cool, I wasn't aware of the homebrew formula. We should probably mention it on the website.

@david0 would be nice if you could write down an accurate description about Calf on MacOSX linking your repository and homebrew so I can put it online @ http://calf-studio-gear.org

**Comment by david0** [comment]
Ok, here it is. I tried to keep it short.

> Its possible to compile calf plugins under Mac OS X. If you are using [homebrew](http://brew.sh), you can use the Formula from the [homebrew-audio tap](https://github.com/david0/homebrew-audio).
> This allows you to use calf plugins under any LV2 capable host or via jack using calfjackhost. Be aware  that the LV2 GTK dos not work reliably, so you should use the generic UI only.

>**Installation using homebrew**
>
>     brew tap david0/homebrew-audio
>     brew install --HEAD calf
 
Feel free to change/modify.

**Comment by boomshop** [comment]
Great, thanks a lot! Will add it to the website asap.

**Comment by boomshop** [comment]
Added.

**Comment by 4471** [comment]
Sorry for this newbie question but where and how should I insert the <formula> on mac Terminal?

**Comment by 4471** [comment]
*the formula

**Comment by matte82** [comment]
Sweet. I got a notification this had been closed. So I tried installing again via Homebrew and it worked perfectly. They're now showing up in Mixbus. Many Thanks David0 or whomever fixed it.

**Comment by david0** [comment]
@matte82: I downloaded the Mixbus demo and the calf plugins are showing up there.

Could you please check if `/usr/local/lib/lv2/calf.lv2` exists and check the output of `lv2ls` for the calf plugins? (lv2ls comes with lilv: `brew install lilv`)
