### ISSUE TITLE
Plugin GUI style : RFC

### ISSUE THREAD

**Issue by distrozapper** [calf-studio-gear/calf#9]
Hi Calf team! Thanks for being there! Your plugins are simply great! But :
Why did you change your plugin's GUI that hard?

The new calf colour theme..nah..too bright and somehow inattractive IMHO. It simply does not make me want to "grab into the screen to turn the knobs" like before. Pity. But I realize maybe you are busy with integrating  more info into the GUI and so you might be urged to find a new GUI style.

Please keep in contact with your users to find the optimum.
Yours sincerely,

Robert Dietrich
distrozapper

**Comment by kfoltman** [comment]
I think the new UI is still not finalized and there might or might not be some minor tweaks in the future if actual, substantial issues are identified.

However, we simply can't consult arbitrary aesthetic decision with the community, there will always be some people who won't like the specific style, or who got seriously attached to the old style and don't want any changes because they hate changes, period. It's difficult enough to find time to develop the features and fix bugs. Both me and Markus are seriously busy with work and life, and  the last thing we want as a team is bike-shedding about UI aesthetics. I don't count functional changes here, of course - we're not going to start removing important features, GNOME 3 style. :)

Keep in mind that if you really hate the new look, you can simply backport the old style to the new version, or hire someone to do that. It shouldn't even be particularly hard to do so.

**Comment by boomshop** [comment]
Because you were asking so nice:

https://github.com/calf-studio-gear/calf/commit/9b7b934f156b6c9fde7d9674c586252df6dd0878

**Comment by kfoltman** [comment]
On 26/06/15 19:22, Markus Schmidt wrote:
>
> Because you were asking so nice:
>
> 9b7b934 
> <https://github.com/calf-studio-gear/calf/commit/9b7b934f156b6c9fde7d9674c586252df6dd0878>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/calf-studio-gear/calf/issues/9#issuecomment-115823764>.
>

Very good. Even better, it doesn't require recompilation - because that 
would be bad for package maintainers.

Some knobs are still a bit flat, say, the settings knob in the Tape 
Simulator. Probably depends on the monitor calibration, mine is 
optimized for text readability so some graphics may suffer. Same for the 
bottom half of the rack buttons - the bottom part of the button more 
'flat' and practically same as background colour comparing to the darker 
upper part. Tested on my screen only, with several different settings 
(movie/game/text).

Really minor nitpick - the English word is magnetic, not magnetical - I 
haven't noticed that before :)

Nice bypass icon with TQFP chip - "we're digital, DEAL WITH IT B-)".

I still have to get back to the pitch shift branch. I have no energy 
anymore due to all the excitement from the hackathon, and my daughter 
wants a large number of 3d printed robots for her school friends for 
Monday :)

About that GTK+ issue - that code example in the article doesn't really 
handle the case where the custom widget is in a dynamic library that can 
be unloaded. That's where the difficulty is, and it affects dynamically 
unloadable GUI code only, so, it doesn't cause problems to almost anyone 
apart from us plugin folks, audio or otherwise.

K.

**Comment by boomshop** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1


> Some knobs are still a bit flat, say, the settings knob in the
> Tape Simulator. Probably depends on the monitor calibration, mine
> is optimized for text readability so some graphics may suffer. Same
> for the bottom half of the rack buttons - the bottom part of the
> button more 'flat' and practically same as background colour
> comparing to the darker upper part. Tested on my screen only, with
> several different settings (movie/game/text).

My monitor is calibrated quite well and over here everything looks
fine now. When you say "optimized for text" I assume a high contrast
setting. This in fact bleaches out shadows and stuff. Could you please
make a photo of your monitor if it's possible?

> Really minor nitpick - the English word is magnetic, not magnetical
> - I haven't noticed that before :)

I used it as a short form for magnetical errors according to this
translator:

http://www.dict.cc/?s=magnetical&=DEEN

That's wrong? And if so - should "mechanical" be renamed, too?

> Nice bypass icon with TQFP chip - "we're digital, DEAL WITH IT
> B-)".

Hehe yes!!1 Have you mentioned the sync button in VintageDelay? This
one I love most.

> I still have to get back to the pitch shift branch. I have no
> energy anymore due to all the excitement from the hackathon, and my
> daughter wants a large number of 3d printed robots for her school
> friends for Monday :)

Oh boy! Lucky fathers live :)

> About that GTK+ issue - that code example in the article doesn't
> really handle the case where the custom widget is in a dynamic
> library that can be unloaded. That's where the difficulty is, and
> it affects dynamically unloadable GUI code only, so, it doesn't
> cause problems to almost anyone apart from us plugin folks, audio
> or otherwise.


Ah okay, I see. Maybe it's the problem addressed here?

https://developer.gnome.org/gtkmm-tutorial/stable/sec-memory-widgets.html.en

But I would like to avoid using Gtkmm - I would switch to Tk or
whatever first..

Best wishes, Markus.

> 
> K.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/calf-studio-gear/calf/issues/9#issuecomment-115870743>.
>
> 
- -- 
Markus Schmidt
schmidt@boomshop.net

boomshop.net
audiovisuelle Medien
Gliesmaroder Straße 9
D-38106 Braunschweig
+49(0)531-34 99 270
info@boomshop.net
http://boomshop.net

GPG: http://boomshop.net/public/Markus_Schmidt.asc
Hash: C228 40CE F2BB 074C 95D4 23A7 A37A 9205 504C 2C21
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlWNuWQACgkQo3qSBVBMLCHmlQCgmnI5rK3Mjx6DkT8Oaj95wlCg
XK8AoNGqUlvGnifj330shgIuJs8J2kcO
=/qVl
-----END PGP SIGNATURE-----

**Comment by kfoltman** [comment]
I'll better lock this thread before more of the off-topic stuff leaks out ;-)

**Comment by kfoltman** [comment]
(actually, it won't help)
